[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-shim"
version = "0.0.0"
description = "Minimal MCP server shim template"
authors = [ { name = "You" } ]

[project.scripts]
mcp-shim = "mcp.__main__:main"

[tool.poetry]
